import { StyleSheet } from 'react-native';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  background: {
    width: '100%',
    aspectRatio: 1.5,
    height: undefined,
  },
  settingsButton: {
    width: 48,
    height: 48,
    top: 46,
    right: 16,
    position: 'absolute',
  },
  card: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    flex: 1,
    justifyContent: 'flex-start',
  },
  imageContainer: {
    position: 'absolute',
    top: -36,
    left: 16,
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'black',
  },
  nameAndEdit: {
    alignSelf: 'stretch',
    marginTop: 37,
    paddingVertical: 17,
    marginHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  userNameText: {
    fontFamily: 'Lato',
    fontWeight: '700',
    fontSize: 22,
    color: '#1A1A1A',
    marginLeft: 6,
  },
  editButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editButtonText: {
    fontFamily: 'Lato',
    fontWeight: '500',
    fontSize: 11,
    color: '#0057B8',
    marginLeft: 4,
  },
  infoBlock: { flex: 1, paddingTop: 16 },
  infoArea: {
    borderWidth: 1,
    borderColor: '#0057B880',
    padding: 15,
    borderRadius: 12,
  },
  infoText: {
    fontFamily: 'Lato',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 18,
    marginVertical: 5,
  },
  separator: {
    height: 1,
    backgroundColor: '#CCCCCC',
    marginVertical: 24,
  },
  donateDetailImageContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
    position: 'absolute',
    width: '100%',
    zIndex: 100,
  },
  donateDetailImage: {
    resizeMode: 'contain',
  },
  donateDetailInfoBlock: {
    backgroundColor: '#ffff',
    position: 'absolute',
    padding: 16,
    zIndex: 10,
  },
  donateDetailInfoBlockUnScrolling: { elevation: 5, borderRadius: 16 },
  donateDetailInfoBlockIsScrolling: {
    elevation: 0,
    borderTopRightRadius: 12,
    borderTopLeftRadius: 12,
  },
  donateDetailInfoBlockTitle: {
    color: '#2D2D2D',
    fontSize: 12,
    fontFamily: 'Lato',
    fontWeight: '400',
  },
  noDonateRecordBlock: {
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  noDonateRecordContainer: {
    backgroundColor: '#EBF1F9',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
  },
  noDonateRecordText: {
    fontFamily: 'Lato',
    fontSize: 16,
    color: '#75787B',
    marginBottom: 12,
  },
  noDonateRecordComponent: { marginBottom: 24 },
  helpWishText: {
    fontFamily: 'Lato',
    fontSize: 24,
    color: '#FF585D',
    marginBottom: 12,
    fontWeight: '700',
  },
  helpWishImage: { marginBottom: 12 },
  helpWishButton: {
    backgroundColor: '#0057B8',
    width: '100%',
    borderRadius: 30,
    alignItems: 'center',
  },
  helpWishButtonText: {
    fontSize: 14,
    marginVertical: 12,
    fontFamily: 'Lato',
    color: '#FFFFFF',
  },
  avatarContainer: {
    width: 80,
    height: 80,
    backgroundColor: '#ffffff',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: -40,
    left: 16,
  },
  guestLoginButton: {
    backgroundColor: '#0057B8',
    position: 'absolute',
    top: -20,
    right: 16,
    padding: 8,
    borderRadius: 30,
    alignItems: 'center',
  },
  guestLoginButtonContainer: {
    marginHorizontal: 12,
    marginVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  guestLoginButtonText: {
    color: '#ffffff',
    fontFamily: 'Lato',
    fontSize: 11,
    marginLeft: 4,
  },
  profileNameBlock: {
    marginTop: 40,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 8,
  },
  profileInfoBlock: {
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  donateRecordTitle: {
    fontFamily: 'Lato',
    fontSize: 16,
    color: '#1A1A1A',
    marginBottom: 16,
  },
  donateRecordBlock: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#0057B880',
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  donateRecordContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  donateRecordTimeText: { marginBottom: 6 },
  donateRecordTitleText: {
    color: '#0057B8',
    fontSize: 16,
    fontFamily: 'Lato',
  },
  donateRecordTotalBlock: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  donateRecordAmountText: {
    color: '#FF585D',
    fontSize: 12,
    marginRight: 24,
  },
  donateRecordExpandSeparator: {
    backgroundColor: '#CCCCCC',
    marginVertical: 12,
  },
});

export default Styles;
