import { StyleSheet } from 'react-native';

const Styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  headerContainer: {
    backgroundColor: '#EBF1F9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  headerTitle: {
    color: '#75787B',
    fontSize: 16,
    fontWeight: '500',
    marginVertical: 28,
  },
  headerFlex: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginVertical: 16,
  },
  goBackButton: { position: 'absolute', left: 0, top: 0 },
  settingTitle: {
    marginBottom: 14,
    marginTop: 10,
    color: '#75787B',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Lato',
  },
  scrollContainer: { marginHorizontal: 16 },
  blockTitle: {
    fontSize: 22,
    fontWeight: '500',
    fontFamily: 'Lato',
    color: '#1A1A1A',
    marginTop: 24,
    marginBottom: 16,
  },
  blockButton: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderColor: '#0057B8',
    borderWidth: 1,
    borderRadius: 50,
    marginBottom: 12,
  },
  buttonFlex: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
  },
  buttonText: {
    color: '#0057B8',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Lato',
    marginLeft: 6,
  },
  separator: {
    height: 2,
    backgroundColor: '#CCCCCC',
    width: '100%',
    marginTop: 12,
  },
  aboutBlockButton: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 12,
  },
  aboutBlockText: {
    color: '#0057B8',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Lato',
    marginVertical: 12,
  },
  logoutButton: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderRadius: 50,
    marginBottom: 40,
    backgroundColor: '#FF585D',
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Lato',
    marginVertical: 14,
  },
  popupModalContainer: {
    position: 'absolute',
    zIndex: 10000,
    backgroundColor: '#00000066',
    flex: 1,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  popupModalContent: { width: '100%', paddingHorizontal: 24 },
  popupModalContentFlex: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
  },
  popupLogoutTitle: {
    color: '#1A1A1A',
    fontFamily: 'Lato',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 16,
  },
  popupLogoutText: {
    color: '#2D2D2D',
    fontFamily: 'Lato',
    fontSize: 14,
    fontWeight: '400',
  },
  popupLogoutOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 24,
  },
  popupLogoutYesButton: {
    borderColor: '#0057B8',
    borderRadius: 50,
    borderWidth: 1,
    marginRight: 8,
  },
  popupLogoutYesButtonText: {
    marginHorizontal: 34,
    marginVertical: 12,
    color: '#0057B8',
  },
  popupLogoutNoButton: {
    backgroundColor: '#0057B8',
    borderRadius: 50,
  },
  popupLogoutNoButtonText: {
    marginHorizontal: 34,
    marginVertical: 12,
    color: '#ffffff',
  },
  welcomeBlock: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 36,
    paddingHorizontal: 16,
    backgroundColor: '#EBF1F9',
    borderRadius: 16,
  },
  welcomeText1: {
    color: '#FF585D',
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Lato',
    marginBottom: 8,
  },
  welcomeText2: {
    color: '#FF585D',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Lato',
    textAlign: 'center',
    marginBottom: 12,
  },
  welcomeModalCloseButton: {
    borderRadius: 50,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0057B8',
    marginBottom: 28,
    marginTop: 16,
  },
  welcomeModalCloseButtonText: {
    fontSize: 14,
    fontFamily: 'Lato',
    marginVertical: 14,
    color: '#ffffff',
  },
});

export default Styles;
